# -*- coding: utf-8 -*-
"""4200MLProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GCR4BIxp60oEKeNtFCTiPzealorlsEn7
"""

import numpy as np
import pandas as pd
import seaborn as sns
#Import dataset

df = pd.read_csv('clean_dataset.csv')

df

#Find number of missing datapoints

df2 = df.dropna();

df2

#Same size -- no missing values

#Aim is to predict whether a customer is 'approved' based on all input factors.

#Credit score, prior default, and debt will be important indicators.

#'Ethnicity' will be interesting to look at and could potentially make for an ethical violation
#if used in the final predictive model.

print(df2['Gender'].value_counts())

# 0 = Female, 1 = Male. Dataset is about 65% male.

sns.displot(data=df2, x='Age')

#Age distribution. Data clustered around 25 with a right-skew. Most data is from 20-40.

sns.displot(data=df2, x='Debt')

#Debt distribution. Data clustered at 0 with most debt less then 5 thousand in total. Local maximum at 11 thousand.

print(df2['Married'].value_counts())

# 1 = Married, 0 = Not Married. ~80% of the dataset is married.

print(df2['BankCustomer'].value_counts())

# 1 = Customer, 0 = Not Customer. ~80% of the dataset is a customer.

sns.displot(data=df2, x='Industry', hue='Industry')

#Added hue for readability. Work industry of the person in consideration. Energy is the most common.

sns.displot(data=df2, x='Ethnicity')

#Ethnicities represented in the dataset. Roughly population-representative with underrepresentation of latino population.

sns.displot(data=df2, x='YearsEmployed')

#Years the person in consideration has been employed. Clustered at 0.

sns.displot(data=df2, x='CreditScore')

#Credit score (scaled down). Mostly 0--indicating no credit score yet.

sns.displot(data=df2, x='Income')

#Income (Scaled down). Again mostly 0.